//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanegeo.SQL.Modelo
{
    using Sanegeo.Dominio;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanegeoEntities : DbContext
    {
        public SanegeoEntities()
            : base("name=SanegeoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aeronave> Aeronaves { get; set; }
        public virtual DbSet<Modelo> Modeloes { get; set; }
    }
}
