//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cos.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int id { get; set; }
        public decimal valor { get; set; }
        public int idOrdemServico { get; set; }
        public int idTipoPagamento { get; set; }
    
        public virtual OrdemDeServico OrdemDeServico { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
    }
}
